[tox]
requires = tox>=4
package_root = {tox_root}

[testenv:formatting]
labels = linting
description = install black in a virtual environment and invoke it on the src folder
skip_install = True
deps=
    black==22.3.0
    isort==5.11.5
commands =
    isort --profile black --check --diff {tox_root}/uac_api
    black -l 88 --check --diff --quiet {tox_root}/uac_api

[testenv:unit_tests]
labels = unit_tests
allowlist_externals = echo
commands =
    echo "Running unit tests"
    echo "Done"

[testenv:build_wheel]
labels = build
skip_install = true
allowlist_externals = find
commands =
    python setup.py sdist bdist_wheel
    find dist/ -name '*.whl' -type f -exec cp -vt ./artifacts/ '{}' +
